name: Run Zap Trigger

on:
  schedule:
    - cron: "30 7 * * *"   # Runs at 07:30 AM UTC (1:00 PM IST)
    - cron: "30 15 * * *"  # Runs at 03:30 PM UTC (9:00 PM IST)
    - cron: "30 23 * * *"  # Runs at 11:30 PM UTC (5:00 AM IST)
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python trigger_zap.py
